/**
 * Fetches CEFR-J vocabulary profiles from GitHub and generates
 * src/lib/difficulty/en-words.json for use in the extension.
 *
 * Sources (open license):
 *   - CEFR-J Vocabulary Profile 1.5 (A1–B2)  — openlanguageprofiles/olp-en-cefrj
 *   - Octanove Vocabulary Profile C1/C2 1.0   — openlanguageprofiles/olp-en-cefrj
 *
 * Run: bun scripts/build-cefr-words.ts
 *   or: npx ts-node scripts/build-cefr-words.ts
 */

import { writeFileSync } from "fs";
import { resolve } from "path";

const SOURCES = [
  "https://raw.githubusercontent.com/openlanguageprofiles/olp-en-cefrj/master/cefrj-vocabulary-profile-1.5.csv",
  "https://raw.githubusercontent.com/openlanguageprofiles/olp-en-cefrj/master/octanove-vocabulary-profile-c1c2-1.0.csv",
];

type CEFRLevel = "A1" | "A2" | "B1" | "B2" | "C1" | "C2";
const LEVEL_ORDER: CEFRLevel[] = ["A1", "A2", "B1", "B2", "C1", "C2"];

function parseCsv(text: string): Array<{ headword: string; cefr: CEFRLevel }> {
  const lines = text.trim().split("\n");
  const header = lines[0].split(",").map((h) => h.trim().toLowerCase());
  const headwordIdx = header.findIndex((h) => h === "headword");
  const cefrIdx = header.findIndex((h) => h === "cefr");

  if (headwordIdx === -1 || cefrIdx === -1) {
    throw new Error(`Missing columns. Headers: ${header.join(", ")}`);
  }

  const results: Array<{ headword: string; cefr: CEFRLevel }> = [];

  for (let i = 1; i < lines.length; i++) {
    const line = lines[i].trim();
    if (!line) continue;

    // Handle quoted fields
    const cols = line.match(/(".*?"|[^,]+)(?=,|$)/g) ?? line.split(",");
    const rawHead = (cols[headwordIdx] ?? "").replace(/^"|"$/g, "").trim();
    const rawLevel = (cols[cefrIdx] ?? "").replace(/^"|"$/g, "").trim() as CEFRLevel;

    if (!rawHead || !LEVEL_ORDER.includes(rawLevel)) continue;

    // Some headwords have alternate forms separated by "/" (e.g. "a.m./am/AM")
    // Also skip multi-word phrases (contain spaces) — they won't match single subtitle tokens
    const variants = rawHead.split("/").map((v) => v.trim().toLowerCase());
    for (const v of variants) {
      if (!v || v.includes(" ")) continue;
      // Only plain alpha + hyphen (no dots, digits)
      if (!/^[a-z'-]+$/.test(v)) continue;
      results.push({ headword: v, cefr: rawLevel });
    }
  }

  return results;
}

async function main() {
  console.log("Fetching CEFR-J datasets...");

  // word → lowest CEFR level seen across all POS entries
  const wordMap = new Map<string, CEFRLevel>();

  for (const url of SOURCES) {
    console.log(`  GET ${url}`);
    const res = await fetch(url);
    if (!res.ok) throw new Error(`Failed to fetch ${url}: ${res.status}`);
    const text = await res.text();

    const entries = parseCsv(text);
    console.log(`  Parsed ${entries.length} entries`);

    for (const { headword, cefr } of entries) {
      const existing = wordMap.get(headword);
      if (!existing || LEVEL_ORDER.indexOf(cefr) < LEVEL_ORDER.indexOf(existing)) {
        wordMap.set(headword, cefr);
      }
    }
  }

  // Group into level buckets
  const output: Record<CEFRLevel, string[]> = {
    A1: [], A2: [], B1: [], B2: [], C1: [], C2: [],
  };

  for (const [word, level] of wordMap.entries()) {
    output[level].push(word);
  }

  // Sort for readability + stable diffs
  for (const level of LEVEL_ORDER) {
    output[level].sort();
    console.log(`  ${level}: ${output[level].length} words`);
  }

  // Output as a TypeScript module (more reliable with WXT/Rollup than JSON import)
  const lines = [
    "// AUTO-GENERATED by scripts/build-cefr-words.ts — do not edit by hand",
    "// Source: openlanguageprofiles/olp-en-cefrj (CC BY-SA 4.0)",
    "",
  ];
  for (const level of LEVEL_ORDER) {
    const words = output[level].map((w) => JSON.stringify(w)).join(",");
    lines.push(`export const ${level}_WORDS: string[] = [${words}];`);
  }
  lines.push("");

  const outPath = resolve(import.meta.dirname ?? __dirname, "../src/lib/difficulty/en-words.ts");
  writeFileSync(outPath, lines.join("\n"));
  console.log(`\nWrote ${outPath}`);
}

main().catch((e) => { console.error(e); process.exit(1); });
