import type { CEFRLevel } from "../types";
import type { LangDifficulty } from "./index";
// Generated by scripts/build-cefr-words.ts — do not edit by hand
// Run: bun scripts/build-cefr-words.ts  to regenerate
import { A1_WORDS, A2_WORDS, B1_WORDS, B2_WORDS, C1_WORDS } from "./en-words";

// ── Build Sets from generated word lists ──────────────────────────────────────
const A1 = new Set<string>(A1_WORDS);
const A2 = new Set<string>(A2_WORDS);
const B1 = new Set<string>(B1_WORDS);
const B2 = new Set<string>(B2_WORDS);
const C1 = new Set<string>(C1_WORDS);

// ── Level classification ──────────────────────────────────────────────────────
const CEFR_ORDER: CEFRLevel[] = ["A1", "A2", "B1", "B2", "C1", "C2"];

function classifyToken(token: string): CEFRLevel {
  if (A1.has(token)) return "A1";
  if (A2.has(token)) return "A2";
  if (B1.has(token)) return "B1";
  if (B2.has(token)) return "B2";
  if (C1.has(token)) return "C1";
  return "C2";
}

function getLevel(word: string): CEFRLevel {
  const lower = word.toLowerCase().replace(/[^a-z-]/g, "");

  // Hyphenated compound words: evaluate each part, return the hardest
  if (lower.includes("-")) {
    const parts = lower.split("-").filter((p) => p.length > 0);
    return parts
      .map(classifyToken)
      .reduce((max, lvl) =>
        CEFR_ORDER.indexOf(lvl) > CEFR_ORDER.indexOf(max) ? lvl : max
      );
  }

  return classifyToken(lower);
}

function levelLabel(level: CEFRLevel): string {
  return level;
}

const placementWords: Record<CEFRLevel, string[]> = {
  A1: ["house", "eat", "big", "friend", "happy", "walk", "water", "day"],
  A2: ["explain", "weather", "important", "travel", "describe", "culture", "manage", "environment"],
  B1: ["accomplish", "perspective", "demonstrate", "significant", "consequence", "investigate", "approximately", "sufficient"],
  B2: ["scrutinize", "meticulous", "unprecedented", "ambiguous", "eloquent", "coherent", "autonomous", "reconcile"],
  C1: ["ephemeral", "perspicacious", "equivocate", "ameliorate", "recalcitrant", "obfuscate", "perfidious", "sycophant"],
  C2: ["solecism", "apophasis", "hendiadys", "tmesis", "antinomy", "synecdoche", "catachresis", "hapax"],
};

export const EN_DIFFICULTY: LangDifficulty = {
  getLevel,
  placementWords,
  levelLabel,
  systemName: "CEFR",
};
